version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: ghcr.io/jcschaff/keycloak-sha1
    environment:
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8443:8443
    volumes:
      - ./conf/server.keystore:/opt/keycloak/conf/server.keystore
    security_opt:
      - 'label:disable'
    command: ["start", "--auto-build", "--db=postgres"]
    depends_on: [db]
