on:
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: Keycloak version
        required: true
      keycloak_sha1_version:
        description: Keycloak SHA-1 version
        required: true
        default: 0.9.0

env:
  REGISTRY: ghcr.io

name: Docker

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./gradlew jar -Pdependency.keycloak.version=${{ github.event.inputs.keycloak_version }}

      - run: cp build/libs/keycloak-sha1-${{ github.event.inputs.keycloak_sha1_version }}.jar docker

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: docker
          build-args: |
            keycloak_version=${{ github.event.inputs.keycloak_version }}
            keycloak_sha1_version=${{ github.event.inputs.keycloak_sha1_version }}
          push: true
          tags: ghcr.io/jcschaff/keycloak-sha1:${{ github.event.inputs.keycloak_version }}_${{ github.event.inputs.keycloak_sha1_version }},ghcr.io/jcschaff/keycloak-sha1:latest
