on:
  workflow_dispatch:
    inputs:
      keycloak_version:
        description: Keycloak version
        required: true
      keycloak_sha1_version:
        description: Keycloak SHA-1 version
        required: true
        default: 1.5.1

name: Docker

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./gradlew jar -Pdependency.keycloak.version=${{ github.event.inputs.keycloak_version }}
      - run: cp build/libs/keycloak-sha1-${{ github.event.inputs.keycloak_sha1_version }}.jar docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: docker
          build-args: |
            keycloak_version=${{ github.event.inputs.keycloak_version }}
            keycloak_sha1_version=${{ github.event.inputs.keycloak_sha1_version }}
          push: true
          tags: jcschaff/keycloak-sha1:${{ github.event.inputs.keycloak_version }}_${{ github.event.inputs.keycloak_sha1_version }},jcschaff/keycloak-sha1:latest
